import type { RuleId } from "../types.js";
import { defineContextualVocabularyRule } from "./private/contextual-vocabulary-rule.js";

const RULE_ID = "words:llm-vocabulary" satisfies RuleId;

const LLM_VOCABULARY = new Set([
  "additionally",
  "align",
  "aligned",
  "aligning",
  "aligns",
  "boast",
  "boasted",
  "boasting",
  "boasts",
  "bolster",
  "bolstered",
  "bolstering",
  "bolsters",
  "comprehensive",
  "crucial",
  "delve",
  "embark",
  "emphasize",
  "emphasized",
  "emphasizes",
  "emphasizing",
  "enduring",
  "enhance",
  "enhanced",
  "enhances",
  "enhancing",
  "excels",
  "foster",
  "fostered",
  "fostering",
  "fosters",
  "garner",
  "garnered",
  "garnering",
  "garners",
  "highlight",
  "highlighted",
  "highlighting",
  "highlights",
  "intricate",
  "intricacies",
  "interplay",
  "key",
  "landscape",
  "meticulous",
  "meticulously",
  "moreover",
  "pivotal",
  "realm",
  "showcase",
  "showcased",
  "showcases",
  "showcasing",
  "tapestry",
  "testament",
  "underscore",
  "underscored",
  "underscores",
  "underscoring",
  "valuable",
  "vibrant",
  "vital"
]);

const rule = defineContextualVocabularyRule({
  description: "LLM vocabulary density",
  minimumHits: 3,
  ruleId: RULE_ID,
  words: LLM_VOCABULARY
});

export default rule;
