import type { RuleId } from "../types.js";
import { defineContextualVocabularyRule } from "./private/contextual-vocabulary-rule.js";

const RULE_ID = "words:llm-vocabulary-density" satisfies RuleId;

const LLM_DENSITY_WORDS = new Set([
  "ai",
  "amplified",
  "amplifies",
  "amplify",
  "amplifying",
  "approach",
  "approaches",
  "authentic",
  "catalyze",
  "catalyzed",
  "catalyzes",
  "catalyzing",
  "causal",
  "complexities",
  "complexity",
  "confidence",
  "correlate",
  "correlated",
  "correlates",
  "correlating",
  "ecosystem",
  "ecosystems",
  "elevate",
  "elevated",
  "elevates",
  "elevating",
  "empirical",
  "empower",
  "empowered",
  "empowering",
  "empowers",
  "engagement",
  "frictionless",
  "generation",
  "holistic",
  "impact",
  "impacts",
  "insight",
  "insights",
  "intentional",
  "learnings",
  "native",
  "navigate",
  "navigates",
  "navigating",
  "next",
  "nuance",
  "nuanced",
  "operationalize",
  "operationalized",
  "operationalizes",
  "operationalizing",
  "resonant",
  "robust",
  "scale",
  "scalable",
  "scales",
  "seamless",
  "stakeholder",
  "stakeholders",
  "strategic",
  "strategies",
  "strategy",
  "sustainable",
  "synergies",
  "touchpoint",
  "touchpoints",
  "transform",
  "transformation",
  "transformative",
  "unlock",
  "unlocking",
  "unlocks",
  "workflow",
  "workflows"
]);

const rule = defineContextualVocabularyRule({
  description: "LLM abstraction vocabulary density",
  minimumHits: 4,
  ruleId: RULE_ID,
  words: LLM_DENSITY_WORDS
});

export default rule;
