import { oneToOneRule } from "../../private/textlint-rule-builders.js";
import { findTripleWordRepeat } from "./private/triple-word-repeat-matcher.js";

const EVALUATIVE_ITEMS = new Set([
  "accessible",
  "adaptable",
  "agile",
  "ambitious",
  "authentic",
  "bold",
  "clear",
  "collaborative",
  "compelling",
  "comprehensive",
  "connected",
  "consistent",
  "credible",
  "deliberate",
  "diverse",
  "durable",
  "dynamic",
  "effective",
  "efficient",
  "empowering",
  "engaging",
  "equitable",
  "fast",
  "flexible",
  "frictionless",
  "future",
  "future-ready",
  "friendly",
  "holistic",
  "impactful",
  "inclusive",
  "innovative",
  "integrated",
  "intentional",
  "intuitive",
  "meaningful",
  "modern",
  "nuanced",
  "powerful",
  "practical",
  "reliable",
  "resonant",
  "ready",
  "resilient",
  "responsive",
  "robust",
  "scalable",
  "seamless",
  "secure",
  "simple",
  "strategic",
  "streamlined",
  "sustainable",
  "thoughtful",
  "transformative",
  "transparent",
  "user-friendly",
  "valuable",
  "vibrant"
]);
const ABSTRACT_ITEMS = new Set([
  "accountability",
  "action",
  "adoption",
  "agility",
  "accessibility",
  "alignment",
  "awareness",
  "change",
  "clarity",
  "collaboration",
  "connection",
  "confidence",
  "consistency",
  "creativity",
  "culture",
  "dedication",
  "diversity",
  "engagement",
  "equity",
  "excellence",
  "experience",
  "flexibility",
  "friction",
  "growth",
  "impact",
  "inclusion",
  "influence",
  "innovation",
  "integration",
  "leadership",
  "mission",
  "momentum",
  "opportunity",
  "progress",
  "purpose",
  "quality",
  "reach",
  "recognition",
  "relevance",
  "resilience",
  "reliability",
  "scalability",
  "security",
  "simplicity",
  "sustainability",
  "synergy",
  "transformation",
  "trust",
  "value",
  "visibility"
]);
const LINKING_VERBS = new Set([
  "are",
  "became",
  "become",
  "becomes",
  "feel",
  "feels",
  "felt",
  "is",
  "remain",
  "remained",
  "remains",
  "seem",
  "seemed",
  "seems",
  "was",
  "were"
]);
const ABSTRACT_LIST_VERBS = new Set([
  "advance",
  "advances",
  "build",
  "builds",
  "combine",
  "combines",
  "create",
  "creates",
  "cultivate",
  "cultivates",
  "deliver",
  "delivers",
  "drive",
  "drives",
  "enable",
  "enables",
  "facilitate",
  "facilitates",
  "generate",
  "generates",
  "improve",
  "improves",
  "inspire",
  "inspires",
  "offer",
  "offers",
  "promote",
  "promotes",
  "promise",
  "promised",
  "promises",
  "shape",
  "shapes",
  "spark",
  "sparks",
  "strengthen",
  "strengthens",
  "support",
  "supports",
  "transform",
  "transforms",
  "unlock",
  "unlocks"
]);
const RHETORICAL_VERBS = new Set([
  "advance",
  "advances",
  "build",
  "builds",
  "create",
  "creates",
  "cultivate",
  "cultivates",
  "deepen",
  "deepens",
  "deliver",
  "delivers",
  "drive",
  "drives",
  "enable",
  "enables",
  "facilitate",
  "facilitates",
  "foster",
  "fosters",
  "generate",
  "generates",
  "improve",
  "improves",
  "inspire",
  "inspires",
  "promote",
  "promotes",
  "promise",
  "promises",
  "reduce",
  "reduces",
  "shape",
  "shapes",
  "spark",
  "sparks",
  "strengthen",
  "strengthens",
  "support",
  "supports",
  "transform",
  "transforms",
  "unlock",
  "unlocks"
]);
const DISCOURSE_SUBJECTS = new Set([
  "agency",
  "approach",
  "brand",
  "business",
  "campaign",
  "company",
  "concept",
  "culture",
  "ecosystem",
  "event",
  "experience",
  "field",
  "framework",
  "initiative",
  "journey",
  "launch",
  "leader",
  "method",
  "mission",
  "model",
  "movement",
  "organization",
  "partnership",
  "platform",
  "process",
  "product",
  "program",
  "project",
  "proposal",
  "redesign",
  "relationship",
  "roadmap",
  "service",
  "solution",
  "strategy",
  "system",
  "team",
  "technology",
  "tool",
  "vision",
  "work"
]);

const rule = oneToOneRule({
  detect: (unit) => {
    const match = findTripleWordRepeat(unit.text, {
      abstractItems: ABSTRACT_ITEMS,
      abstractListVerbs: ABSTRACT_LIST_VERBS,
      discourseSubjects: DISCOURSE_SUBJECTS,
      evaluativeItems: EVALUATIVE_ITEMS,
      linkingVerbs: LINKING_VERBS,
      rhetoricalVerbs: RHETORICAL_VERBS
    });
    if (match === undefined) {
      return [];
    }

    return [
      {
        evidence: unit.text.slice(match.start, match.end),
        label: "triple-word-repeat",
        range: match
      }
    ];
  },
  family: "syntactic-patterns",
  formatMessage: (report) =>
    `Formulaic three-part list found: "${report.evidence}". Keep only distinctions that carry concrete information.`,
  ruleId: "syntactic-patterns:triple-word-repeat",
  unitKind: "sentence"
});

export default rule;
